### ISSUE TITLE
Questions Regarding Live Activity

### ISSUE THREAD

**Issue by ghost** [pookjw/DynamicAlert#2]
https://github.com/pookjw/DynamicAlert/blob/fae66a7524d557cc54e1690472164c080c19b575/DynamicAlertSpringBoard/da%2BsbTools.mm#L49

Hello, I've previewed your code. This part is a bit unclear to me. It seems like it's attempting to retrieve the primary live activity, and if there are no live activity present, does this mean that your custom alert cannot be displayed?

**Comment by pookjw** [comment]
`-[UIApplication systemApertureControllerForMainDisplay]` returns `SBSystemApertureController` which is manages Activities of Dynamic Island.

> It seems like it's attempting to retrieve the primary live activity, and if there are no live activity present, does this mean that your custom alert cannot be displayed?

No, it creates a new Activity at [here](https://github.com/pookjw/DynamicAlert/blob/fae66a7524d557cc54e1690472164c080c19b575/DynamicAlertSpringBoard/DASceneHandleObserver.mm#L68).

If creation was successful, `SBSAContainerViewDescription`, `SBSAViewDescription`, `SAUIElementView`... will be called. You need to hook them to add Custom View into Activity View. [main.mm](https://github.com/pookjw/DynamicAlert/blob/main/DynamicAlertSpringBoard/main.mm)

**Comment by ghost** [comment]
> `-[UIApplication systemApertureControllerForMainDisplay]`返回`SBSystemApertureController`管理动态岛活动的回报。
> 
> > 它似乎正在尝试检索主要的实时活动，如果不存在实时活动，这是否意味着无法显示您的自定义警报？
> 
> [不，它在这里](https://github.com/pookjw/DynamicAlert/blob/fae66a7524d557cc54e1690472164c080c19b575/DynamicAlertSpringBoard/DASceneHandleObserver.mm#L68)创建一个新的活动。
> 
> 如果创建成功，将调用`SBSAContainerViewDescription`、`SBSAViewDescription`、 ...。您需要将它们挂钩以将自定义视图添加到活动视图中[。main.mm](https://github.com/pookjw/DynamicAlert/blob/main/DynamicAlertSpringBoard/main.mm)`SAUIElementView`[](https://github.com/pookjw/DynamicAlert/blob/main/DynamicAlertSpringBoard/main.mm)

Apologies, I'm not very familiar with Objective-C++, Thank you for taking the time to reply to me.❤️❤️❤️❤️❤️❤️❤️
